# Generated by Django 4.1.3 on 2022-11-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0002_menuitem_spicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='label',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='cuisine',
            old_name='name',
            new_name='title',
        ),
    ]
